MOVIES = {
    1: {
        'id': 1,
        'title': 'Phi Vụ Động Trời 2 - ZOOTOPIA 2',
        'image': 'movie1.jpg',
        'director': 'Jared Bush, Byron Howard',
        'cast': 'Jason Bateman, Quinta Brunson, Fortune Feimster',
        'genre': 'Gia đình, Hành động, Phiêu lưu, Thần thoại',
        'release_date': '28/11/2025',
        'duration': '120 phút',
        'language': 'Tiếng Anh - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '13+',
        'rating': '8.5/10',
        'price': '80.000₫',
        'description': 'Tiếp nối những cuộc phiêu lưu hài hước và cảm động, Zootopia 2 đưa khán giả vào một hành trình mới đầy bất ngờ và thông điệp ý nghĩa về tình bạn và công lý.'
    },
    2: {
        'id': 2,
        'title': 'CHÚ THUẬT HỒI CHIẾN: BIẾN CỐ SHIBUYA',
        'image': 'movie2.jpg',
        'director': 'Park Sunghoo',
        'cast': 'Yuuichi Nakamura, Asami Seto, Junya Enoki',
        'genre': 'Anime, Hành động, Siêu nhiên, Kỳ ảo',
        'release_date': '24/12/2024',
        'duration': '144 phút',
        'language': 'Tiếng Nhật - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '16+',
        'rating': '9.0/10',
        'price': '100.000₫',
        'description': 'Một hành trình gay cấn đan xen các trận chiến tâm linh, nơi các nhân vật phải đối mặt với quá khứ và thay đổi số phận.'
    },
    3: {
        'id': 3,
        'title': 'CHAINSAW MAN - THE MOVIE: CHƯƠNG REZE',
        'image': 'movie3.jpg',
        'director': 'Motonobu Hori',
        'cast': 'Kikunosuke Toya, Maaya Uchida, Tomokazu Seki',
        'genre': 'Anime, Hành động, Kinh dị, Hài hước',
        'release_date': '15/02/2025',
        'duration': '109 phút',
        'language': 'Tiếng Nhật - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '18+',
        'rating': '8.8/10',
        'price': '110.000₫',
        'description': 'Sự kết hợp giữa bạo lực, hài hước và cảm xúc mạnh mẽ tạo nên trải nghiệm mãnh liệt cho người xem.'
    },
    4: {
        'id': 4,
        'title': 'THANH GƯƠM DIỆT QUỶ : VÔ HẠN THÀNH',
        'image': 'movie4.jpg',
        'director': 'Haruo Sotozaki',
        'cast': 'Natsuki Hanae, Akari Kitou, Hiro Shimono',
        'genre': 'Anime, Hành động, Giả tưởng, Siêu nhiên',
        'release_date': '31/12/2024',
        'duration': '110 phút',
        'language': 'Tiếng Nhật - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '18+',
        'rating': '9.8/10',
        'price': '125.000₫',
        'description': 'Một chương mới với những trận chiến gay cấn và cảm xúc cao trào, dành cho fan của series.'
    },
    5: {
        'id': 5,
        'title': 'Năm Đêm Kinh Hoàng 2',
        'image': 'movie5.jpg',
        'director': 'Emma Tammi',
        'cast': 'Josh Hutcherson, Matthew Lillard, Piper Rubio',
        'genre': 'Kinh dị, Bí ẩn, Hồi hộp',
        'release_date': '14/12/2024',
        'duration': '115 phút',
        'language': 'Tiếng Anh - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '18+',
        'rating': '8.5/10',
        'price': '95.000₫',
        'description': 'Tiếp tục chuỗi sự kiện rùng rợn, phần 2 hứa hẹn nhiều giật gân hơn cùng những twist không ngờ.'
    },
    6: {
        'id': 6,
        'title': 'AVATAR : Lửa và Tro tàn',
        'image': 'movie6.jpg',
        'director': 'James Cameron',
        'cast': 'Sam Worthington, Zoe Saldana, Sigourney Weaver',
        'genre': 'Khoa Học Viễn Tưởng, Phiêu Lưu, Sử thi',
        'release_date': '20/12/2024',
        'duration': '110 phút',
        'language': 'Tiếng Anh - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '18+',
        'rating': '9.5/10',
        'price': '150.000₫',
        'description': 'Một hành trình sử thi, đồ họa hoành tráng và thông điệp về thiên nhiên cùng sự tồn vong.'
    },
    7: {
        'id': 7,
        'title': '5 CENTIMET TRÊN GIÂY',
        'image': 'movie7.jpg',
        'director': 'Makoto Shinkai',
        'cast': 'Yoshito Isomaki, Mika Shinoda, Kaito Ishikawa',
        'genre': 'Hoạt Hình, Tình cảm, Kiếp nào ta',
        'release_date': '28/11/2024',
        'duration': '76 phút',
        'language': 'Tiếng Nhật - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '13+',
        'rating': '8.7/10',
        'price': '100.000₫',
        'description': 'Câu chuyện nhẹ nhàng, cảm xúc về những khoảnh khắc nhỏ bé nhưng ý nghĩa trong cuộc sống.'
    },
    8: {
        'id': 8,
        'title': 'Conan : Dư Ảnh Của Độc Nhãn',
        'image': 'movie8.jpg',
        'director': 'Yuzuru Tachikawa',
        'cast': 'Minami Takayama, Wakana Yamazaki, Ai Ota',
        'genre': 'Hành Động, Hoạt Hình, Giải đố',
        'release_date': '27/10/2024',
        'duration': '117 phút',
        'language': 'Tiếng Nhật - Phụ đề Tiếng Việt; Lồng tiếng Việt',
        'age_rating': '13+',
        'rating': '9/10',
        'price': '90.000₫',
        'description': 'Một bộ phim hành động giải đố cùng các pha rượt đuổi kịch tính và những tình tiết hợp lý bất ngờ.'
    }
}
